[package]
name = "x-bounty-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.x-bounty]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.6"
default-features = false
